blueprint:
  name: ClimateSchedule
  source_url: https://github.com/mkorpar/ha/blob/main/climate-schedule.yaml
  domain: automation
  input:
    climate_input:
      name: Climate
      selector:
        entity:
          multiple: false
          domain: climate
    schedule:
      name: Schedule
      selector:
        entity:
          multiple: false
          domain: schedule
    default_temp:
      name: Default temperature
      default: 18
      selector:
        number:
          min: 5
          max: 25
          unit_of_measurement: "°C"

triggers:
  - trigger: state
    entity_id: !input schedule

trigger_variables:
  _climate_input: !input climate_input

conditions:
  - condition: "{{ state_attr(_climate_input, 'hvac_action') != 'off' }}"

actions:
  - variables:
      schedule: !input schedule
  - if:
      - condition: state
        entity_id: !input schedule
        state: "on"
    then:
      - action: climate.set_temperature
        metadata: {}
        data:
          temperature: "{{ state_attr(schedule, 'temperature') }}"
        target:
          entity_id: !input climate_input
    else:
      - action: climate.set_temperature
        metadata: {}
        data:
          temperature: 22
        target:
          entity_id: !input climate_input
mode: single
