blueprint:
  name: ClimateSchedule
  source_url: https://github.com/mkorpar/ha/blob/main/climate-schedule.yaml
  domain: automation
  input:
    climate_input:
      name: Climate
      selector:
        entity:
          multiple: false
          domain: climate
    schedule:
      name: Schedule
      selector:
        entity:
          multiple: false
          domain: schedule
    default_temp:
      name: Default temperature
      default: 18
      selector:
        number:
          min: 5
          max: 25
          unit_of_measurement: "°C"

triggers:
  - trigger: state
    entity_id: !input schedule

trigger_variables:
  _climate_input: !input climate_input

conditions:
  - condition: template
    value_template: "{{ state_attr(_climate_input, 'hvac_action') != 'off' }}"

actions:
  - variables:
      schedule: !input schedule
      climate_input: !input climate_input
      default_temp: !input default_temp
  - if:
      - condition: state
        entity_id: !input schedule
        state: "on"
    then:
      - action: climate.set_temperature
        metadata: {}
        data:
          temperature: "{{ state_attr(schedule, 'temperature') }}"
        target:
          entity_id: !input climate_input
    else:
      - repeat:
          while:
            - condition: template
              value_template: "{{ state_attr(climate_input, 'temperature') != default_temp  }}"
          sequence:
            - action: climate.set_temperature
              metadata: {}
              data:
                temperature: !input default_temp
              target:
                entity_id: !input climate_input
            - delay:
              hours: 0
              minutes: 0
              seconds: 5
              milliseconds: 0
mode: single
