blueprint:
  name: WindowOpenedToTRV
  source_url: https://github.com/mkorpar/ha/blob/main/heating-windows.yaml
  domain: automation
  input:
    window_sensors:
      name: Window sensors
      selector:
        entity:
          multiple: true
          device_class: opening
          domain: binary_sensor
    trv_window_opened:
      name: TRV window opened switch
      selector:
        entity:
          multiple: false
          domain: switch
        
conditions: []
  
triggers:
  - trigger: state
    entity_id: !input window_sensors

actions:
  - variables:
      sensors: !input window_sensors
  - if:
      - condition: template
        value_template: >-
          {{sensors | select('is_state', 'on') | list | length > 0}}
    then:
      - action: switch.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: !input trv_window_opened
    else:
      - action: switch.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: !input trv_window_opened

mode: single
