blueprint:
  name: WindowOpenedToTRV
  source_url: https://github.com/mkorpar/ha/blob/main/heating-windows.yaml
  domain: automation
  input:
    window_sensors:
      name: Window sensors
      selector:
        entity:
          multiple: true
          device_class: opening
          domain: binary_sensor
    trv_window_opened:
      name: TRV window opened switch
      selector:
        entity:
          multiple: false
          domain: switch
        
conditions: []
  
triggers:
  - trigger: state
    entity_id: !input window_sensors

actions: []

mode: single
